# -*- coding: utf-8 -*-
"""A4_A-56_KrishnaKondekar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKHVnkVrZvfe6VMIsXdbPPfuONlsjK0O

<h1>Assignment – 3: Data Wrangling with pandas</h1>

**Aim**:Data Wrangling with pandas, Manipulate and transform data to suit the analysis

**Theory:**

Making raw data usable is no simple task — it requires a series of deliberate steps collectively known as data wrangling, or sometimes data munging. This involves scrubbing, reshaping, and reorganizing messy input into a clean, structured format that is actually fit for analysis. Because data collected from the real world tends to be riddled with missing entries, conflicting values, or no clear structure whatsoever, getting through this stage is non-negotiable before any analysis or model building can begin.

To bring these ideas to life, this assignment constructs a Pandas DataFrame from scratch, deliberately introducing missing values in the 'Name', 'Age', and 'Score' columns. The `isnull()` function was then applied to track down exactly where these gaps existed, which laid the groundwork for targeted fixes. Where 'Age' values were absent, they were replaced with the column's calculated mean using `fillna()`, keeping the dataset intact without losing rows unnecessarily. In contrast, any row missing a 'Name' entry was dropped altogether via `dropna()`, since such records were considered too incomplete to be of use.

Wrangling, however, is not limited to just fixing what is broken — it also involves actively reshaping data into more informative forms. A clear example of this is the introduction of a 'Status' column, whose values were assigned based on conditions drawn from the 'Score' column. This kind of derived feature creation is what practitioners call column transformation, and it sits at the heart of feature engineering.

Rounding out the assignment is a discussion on Exploratory Data Analysis, or EDA — a critical phase where analysts examine how data behaves, search for hidden patterns, and flag anything that looks out of place, all in service of making smarter decisions down the line. A quick introduction to Pandas' built-in data structures is also provided: the single-dimensional Series, the table-like two-dimensional DataFrame, and the three-dimensional Panel, which has largely fallen out of use in modern practice.

**5. Column Transformation:**

Column transformation refers to the operation of altering existing columns or deriving entirely new columns from the data already present within a dataset.

1.  This involves either modifying the values inside current columns or producing novel columns.
2.  It aids in feature engineering by constructing more informative variables for analysis.
3.  By providing a richer representation of the underlying problem, it can enhance predictive model efficacy.
4.  Examples include scaling numerical data, encoding categorical attributes, performing mathematical calculations, or applying custom functions.
5.  Its utility lies in converting unrefined data into a format better suited for deep analysis or machine learning applications.
"""

import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values for demonstration
data = {
    'Name': ['Sarang', 'Amit', 'Rohit', 'Neha', None],
    'Age': [20, 22, np.nan, 21, 23],
    'Score': [85, np.nan, 90, 88, 75]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)


print("\nIs Null Check:")
print(df.isnull().sum())

# 4d: Fill missing Age with the mean Age (Data Wrangling step)
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 4c: Drop rows where Name is missing
df = df.dropna(subset=['Name'])

# 5: Column Transformation (Example: Adding a 'Status' column)
# If score > 80, Status is 'Pass', else 'Average'
df['Status'] = df['Score'].apply(lambda x: 'Pass' if x > 80 else 'Average')

print("\nWrangled DataFrame:")
print(df)

"""**1. What is data wrangling?**

Data wrangling, also known as data munging, is the critical process of converting raw, often untidy data into a cleaner, more structured, and accessible format, thereby enhancing its utility for analytical purposes.

**Key Aspects of Data Wrangling:**

1.  Encompasses the comprehensive activities of cleaning, structuring, and transforming unrefined data.
2.  Aims to achieve data uniformity, utility, and proper organization.
3.  Involves operations such as managing missing entries, eliminating redundant records, combining disparate datasets, and rectifying data formats.
4.  Its primary objective is to make data readily available and suitable for examination.

**Distinction from Data Preprocessing:**

1.  Data preprocessing is a subsequent, more specialized phase typically performed after wrangling.
2.  Its focus is on tailoring data specifically for machine learning algorithms.
3.  Techniques include data scaling, normalization, converting categorical data, and feature selection.
4.  The main purpose is to adapt data into an algorithm-compatible format.
<br>

**2. Importance of Exploratory Data Analysis (EDA):**

Exploratory Data Analysis (EDA) is an investigative procedure where a dataset is examined and condensed to grasp its fundamental properties, frequently utilizing statistical and graphical approaches prior to model development.

**Benefits of EDA:**

1.  Provides a concise overview of a dataset's essential attributes.
2.  Leverages graphical representations, such as plots and charts.
3.  Facilitates the identification of underlying trends and correlations within the data.
4.  Helps in detecting unusual observations, extreme values, and inconsistencies.
5.  Allows for the validation of initial hypotheses before formal analytical modeling.
6.  Contributes to more informed analytical choices.
7.  Commonly executed with libraries like Pandas.
<br>

**3. Main Differences: Series, DataFrame, and Panel:**

  Series: A one-dimensional, labeled array designed to store various data types.

  DataFrame: A two-dimensional, labeled tabular data structure where columns can have diverse data types, akin to a relational table or spreadsheet.

  Panel: A three-dimensional data container, which is now largely superseded in contemporary Pandas by the use of MultiIndex DataFrames.

**4. Explain the use of:**

  a. `isnull()`: Identifies the presence of null or missing data points; it generates a boolean structure mirroring the original data's dimensions.

  b. `notnull()`: Serves as the inverse of `isnull()`; it yields `True` for existing, non-missing values.

  c. `dropna()`: Eliminates rows or columns that contain any missing data from the dataset.

  d. `fillna()`: Populates missing data entries with either a user-specified constant or an aggregated value, such as an average.

**5. Column Transformation:**

Column transformation is the process of modifying existing columns or creating new columns from existing data in a dataset.

1. Involves changing values within existing columns or generating new ones
2. Helps in feature engineering by creating more meaningful variables
3. Improves model performance by better representing the problem
4. Can include operations like scaling, encoding, arithmetic operations, or applying functions
5. Useful for converting raw data into a more usable form for analysis or machine learning

**Conclusion:**

This assignment effectively illustrates the application of data wrangling techniques to refine and reshape raw data into a coherent and interpretable structure. The exercise covered the detection and proper management of missing data points, alongside the elimination of superfluous or incomplete records. Furthermore, a new column was generated, showcasing how data transformation can enrich a dataset.

The workflow underscores the paramount importance of data preparation prior to any analytical endeavor. A clean and logically structured dataset is instrumental in yielding precise insights and boosting the predictive power of models. Consequently, data wrangling stands as an indispensable phase in any data analysis or data science pipeline.
"""

