# -*- coding: utf-8 -*-
"""A4_A-56_KrishnaKondekar..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7D2NbpK3eaNnwCZY02pD99_PLDuWPaN

<h1>Assignment – 5: Data Visualization with Matplotlib

**Aim**: Data Visualization with Matplotlib, Data visualization on a dataset using matplotlib

**Theory**:

Turning raw data into visual graphics — through tools like charts, graphs, and plots — is what data visualization is all about. Rather than staring at rows and columns of numbers, users can spot patterns, trends, connections, and unusual values far more quickly when information is presented in a graphical form. Two Python libraries commonly used to achieve this are Matplotlib and Seaborn, both of which are put to use in this assignment.

Matplotlib acts as the backbone of the plotting process, providing the core functionality needed to construct a wide range of graphics. Seaborn, built on top of Matplotlib, takes things a step further by delivering cleaner, more attractive, and statistically enriched visuals while requiring considerably less code to do so. Through Matplotlib's `pyplot` module, developers gain access to an intuitive interface capable of producing line charts, bar graphs, histograms, scatter plots, and more.

A variety of plot types are explored across this assignment, each serving a distinct purpose:

- **Scatter Plots** uncover the nature of relationships between two variables — for example, how sepal length and sepal width interact within the Iris dataset.
- **Bar Plots** make it straightforward to draw comparisons across different categories or groups by placing their values side by side.
- **Histograms** shed light on how frequently values appear within a given range, illustrated here through the distribution of petal length measurements.
- **Box Plots** summarize data spread and draw attention to values that fall outside the expected range, applied here to compare petal width across different species.
- **Pair Plots** take a wide-angle view, mapping out the relationships between every numerical variable in the dataset all at once.

Making a visualization look good is just as important as making it accurate. Proper titles, descriptive axis labels, thoughtful color schemes, and layout refinements — handled through tools like `set_title()`, `figsize`, and `tight_layout()` — transform a basic plot into something both readable and polished.

Altogether, data visualization serves as a powerful companion to Exploratory Data Analysis, cutting through complexity and giving analysts a clearer picture of their data before diving into more advanced techniques or building predictive models.

**Q1 — Importance of data visualization in EDA**

Data visualization converts raw numbers into graphical form, making it easier to understand patterns, trends, and relationships. In EDA, it helps detect outliers, understand distributions, identify correlations between variables, and spot missing data — all before applying any model. The human brain processes visuals much faster than tables of numbers, so visualization speeds up the entire analysis process.

---

**Q2 — Matplotlib vs other visualization libraries**

Matplotlib is a low-level, highly customizable library that gives full control over every element of a plot, but requires more code. Seaborn is built on top of Matplotlib and provides simpler, statistically-focused plots with better default styles. Plotly and Bokeh create interactive, web-ready charts (zoom, hover, pan), while Matplotlib produces static images. Pandas `.plot()` is just a shortcut wrapper over Matplotlib for quick plots on DataFrames.

---

**Q3 — Purpose of the pyplot module**

`matplotlib.pyplot` (aliased as `plt`) provides a simple, MATLAB-style interface to Matplotlib. It maintains a "current figure" state so you can build a plot step by step using functions like `plt.plot()`, `plt.title()`, `plt.xlabel()`, and `plt.show()` without manually managing figure and axes objects. It is mainly used for quick, interactive plotting.

---

**Q4 — Creating a basic line plot**

1. Import the library: `import matplotlib.pyplot as plt`
2. Prepare x and y data (lists or arrays)
3. Call `plt.plot(x, y)` to draw the line
4. Add labels: `plt.title()`, `plt.xlabel()`, `plt.ylabel()`
5. Optionally add `plt.legend()` and `plt.grid(True)`
6. Display with `plt.show()`

Multiple lines can be added by calling `plt.plot()` again before `plt.show()`.

---

**Q5 — Importance of customization in Matplotlib**

Without customization, plots lack context and clarity. Proper labels, titles, colors, and formatting make a chart readable, professional, and meaningful to the audience. Matplotlib offers extensive options including colors (`color=`, `cmap=`), line styles (`linestyle=`, `linewidth=`), markers (`marker=`), axis limits (`plt.xlim()`, `plt.ylim()`), tick labels (`plt.xticks()`), annotations (`plt.annotate()`), figure size (`figsize=`), global styles (`plt.style.use()`), and saving (`plt.savefig()`). Good customization ensures the visualization communicates the right insight clearly.

**Conclusion**:

This assignment highlights the effectiveness of data visualization in comprehending and interpreting complex datasets. Through various plots generated using Matplotlib and Seaborn, relationships, distributions, and patterns within the data were thoroughly explored.

The application of diverse visualization techniques facilitated a clearer analysis of the data, leading to the identification of key insights and trends. Furthermore, thoughtful customization significantly improved the clarity and overall presentation quality of the visualizations.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

x = np.linspace(0, 10, 20)
y = x ** 2
categories = ['A', 'B', 'C', 'D']
values = [5, 7, 3, 8]

plt.figure(figsize=(8, 4))
plt.plot(x, y, label='Growth Curve', color='green', marker='o')
plt.title("Basic Line Plot")
plt.xlabel("Time")
plt.ylabel("Value")
plt.legend()
plt.show()

df_iris = sns.load_dataset('iris')

sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

sns.scatterplot(data=df_iris, x='sepal_length', y='sepal_width', hue='species', ax=axes[0, 0])
axes[0, 0].set_title("Scatter Plot: Sepal Dimensions")

axes[0, 1].bar(categories, values, color='skyblue')
axes[0, 1].set_title("Bar Plot: Categories")

sns.histplot(df_iris['petal_length'], bins=15, kde=True, ax=axes[1, 0], color='purple')
axes[1, 0].set_title("Histogram: Petal Length Distribution")

sns.boxplot(data=df_iris, x='species', y='petal_width', ax=axes[1, 1])
axes[1, 1].set_title("Box Plot: Petal Width by Species")

plt.tight_layout()
plt.show()

print("Generating Pair Plot...")
sns.pairplot(df_iris, hue='species')
plt.show()