# -*- coding: utf-8 -*-
"""krishna kondekar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcZtCUTnoqDtz1y4R1eA3gmjdQbhptmc

<h1>Assignment - 2 : Data Ingestion and Cleaning</h1>

**Aim**: Data Ingestion and Cleaning: Acquire data and prepare it for analysis.


**Theory**:

This assignment explores data ingestion and cleaning, fundamental steps in preparing data for analysis. Data ingestion involves gathering and importing raw data from various origins, such as CSVs, databases, or APIs, into a usable system. Here, the Titanic dataset was loaded into a Pandas DataFrame using `read_csv()`, with `head()` and `tail()` providing initial insights into its structure. Data cleaning addresses errors and inconsistencies in datasets, a common necessity given the imperfect nature of real-world data. This process includes detecting and rectifying issues like missing values, duplicates, or format errors. For instance, the Titanic dataset showed missing values in 'Age', 'Cabin', and 'Embarked', identified using `isnull()` and `sum()`. Effective data cleaning is crucial for enhancing data accuracy, ensuring consistency, and making the dataset fit for analytical and machine learning purposes. Ultimately, ingestion and cleaning together lay the groundwork for data preprocessing, transforming raw information into a dependable and analytical-ready state.
"""

import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv" #dataset
df = pd.read_csv(url)

print("Data Loaded")
print("\nFirst 5 rows (head):")
print(df.head())
print("\nLast 5 rows (tail):")
print(df.tail())

missing_data = df.isnull().sum()

print("Missing values per column:")
print(missing_data)

total_cells = df.size
total_missing = missing_data.sum()
print(f"\nTotal missing values in dataset: {total_missing}")

"""**1. What is data ingestion?**

Definition: Data ingestion refers to the procedure of gathering and transferring raw data from diverse origins (like CSVs, databases, or APIs) into a data system, typically for processing, analysis, or archiving.

Types:
Batch ingestion: Data is accumulated and transferred in discrete blocks periodically.
Real-time ingestion: Data is captured and moved continuously as it becomes available.
Sources: Various data origins including files (e.g., CSV, Excel), relational and non-relational databases, application programming interfaces (APIs), and live data streams.

Tools: Python's Pandas library is a frequent choice for straightforward data ingestion tasks.

Significance:
1. Renders data accessible for subsequent analytical activities.
2. Facilitates informed decision-making processes.
3. Guarantees efficient operation of data pipelines.
4. Key hurdles: Managing voluminous data, reconciling disparate formats, and maintaining data integrity.


<br>

**2. Why is data cleaning necessary?**

Definition: Data cleaning is the systematic process of detecting and rectifying imperfections or inaccuracies within raw datasets.

Typical problems encountered:
1. Gaps in data (represented as NaN or null).
2. Redundant data entries.
3. Misformatted data types (e.g., numerical values stored as strings).
4. Anomalous observations or erroneous data points.

Importance:

Data cleaning is vital for boosting the precision of analytical insights, ensuring the robustness of machine learning algorithms, and avoiding skewed or erroneous outcomes. This critical phase encompasses strategies such as imputing or removing absent data, eliminating identical entries, transforming data into appropriate types, and harmonizing values to achieve uniformity throughout the dataset.

Tools:
Pandas, among other libraries, is extensively utilized for effective data sanitization.

<br>

**3. How do you load a CSV file into a Pandas DataFrame?**

To import a CSV file into a Pandas DataFrame, one employs the `read_csv()` function provided by the Pandas library. The process typically involves importing Pandas, then passing the location (file path or URL) of the CSV file to this function. This action parses the CSV data and structures it into a DataFrame, making it ready for data manipulation and analysis.

**What is the difference between head() and tail() functions in Pandas?**

**`head()` in Pandas:**
This method retrieves the initial `n` rows of a DataFrame, with a default return of the first 5 rows if no argument is provided.

Syntax: `df.head(n)`

Purpose:
1. Provides a quick snapshot of the dataset's beginning.
2. Aids in examining column labels and overall data layout.
3. Helps in gaining an initial grasp of the data content.

**`tail()` in Pandas:**
This function extracts the final `n` rows of a DataFrame; it defaults to showing the last 5 rows when no specific number `n` is given.

Syntax: `df.tail(n)`

Utility:
1. Offers a view of the dataset's concluding records.
2. Useful for verifying data integrity, especially for completeness.
3. Allows for inspection of the most recent or final data points.

**5. How can you identify missing values in a dataset?**

In Pandas, detecting absent data points (often represented as null or NaN) within a dataset can be achieved using several integrated functions.

Primary techniques include:
1. `isnull()` / `isna()`:
These methods yield a DataFrame populated with Boolean values, indicating `True` where data is absent and `False` otherwise.

2. Combining `isnull()` with `sum()`:
This combination provides a count of all missing entries for each respective column in the dataset.

Based on the code output above:

    The df.isnull().sum() function allows us to see exactly which columns need cleaning.

    In the Titanic dataset, you will likely see missing values in 'Age', 'Cabin', and 'Embarked'.

**Conclusion**:

This assignment underscores the critical importance of data ingestion and cleaning as foundational stages in any data analysis workflow. We successfully acquired and initially examined the dataset, pinpointing areas with absent values. Thorough data cleaning is paramount for elevating data quality and securing reliable analytical outcomes. In essence, a meticulously prepared and clean dataset is indispensable for achieving superior analytical insights and supporting sound decision-making.
"""