# -*- coding: utf-8 -*-
"""krishna kondekarSDSPR8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bm3gXbKvNxJw9Icq8XR4VSXNRx0D1D1t
"""



"""# PDS PRACTICAL 8

**NAME: Krishna Mahendra Kondekar**

**DIV: SY-A**

**ROLL NO.: A-56**

**AIM: To implement and analyze different methods of studying correlation and regression, including Karl Pearson’s coefficient and simple linear regression using Python.**

**1. What is correlation? How is it different from regression?**

Correlation measures the strength and direction of the relationship between two variables. It tells whether variables move together (positive, negative, or no relation).

Regression, on the other hand, is used to predict the value of one variable based on another. It establishes a mathematical relationship between dependent and independent variables.

Difference:

* Correlation → measures relationship (no prediction)

* Regression → used for prediction

* Correlation is symmetric (X & Y same)

* Regression is directional (X predicts Y)

**2. What is simple linear regression? Explain with suitable example.**

Simple linear regression is a method used to model the relationship between two variables using a straight line equation:

y = mx + c

Where:

-y = dependent variable

-x = independent variable

-m = slope

-c = intercept

It tries to find the best-fit line that minimizes error.

Example:
If you study hours (X) and marks (Y), regression helps predict marks based on study hours.

**3. How do you calculate Pearson correlation in Python?**

Pearson correlation measures linear relationship between two variables and ranges from -1 to +1.

Formula:
r = covariance(X,Y) / (σx * σy)

In Python, it is calculated using libraries like NumPy or Pandas.

**4. What is multicollinearity? Does it affect simple regression?**

Multicollinearity occurs when independent variables are highly correlated with each other.

It mainly affects multiple regression, not simple regression.

In simple regression, there is only one independent variable, so multicollinearity does not occur.

But in multiple regression, it can:

* distort coefficients
* reduce model reliability


**5. A dataset shows strong correlation but poor prediction accuracy. Why?**

This usually happens because:

* Correlation only measures linear relationship, not prediction accuracy
* Data may have outliers affecting regression
* Relationship may be non-linear
* Overfitting or underfitting issues
* High variance in data
"""

import pandas as pd

df = pd.read_csv("/content/train (1).csv")

df = df[['Age', 'Fare', 'Survived']]

df = df.dropna()

print(df.head())

correlation = df.corr()

print("Correlation Matrix:\n")
print(correlation)

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


X = df[['Age']]
y = df['Fare']

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)

plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("Age")
plt.ylabel("Fare")
plt.title("Regression: Age vs Fare")
plt.show()

# Check correlation with survival
print(df[['Survived', 'Age', 'Fare']].corr())

"""**Conclusion:**

The Titanic dataset was analyzed using correlation and regression techniques. Pearson correlation showed the relationship between variables such as Age, Fare, and Survival. It was observed that correlations are not very strong due to the complex nature of real-world data.

Simple linear regression was used to predict Fare based on Age, but the prediction accuracy was limited because the relationship is not strictly linear and depends on multiple factors.

Thus, correlation alone is not sufficient for prediction, and regression models must consider multiple variables for better accuracy.
"""